### ISSUE TITLE
ApiError: Missing query parameter type

### ISSUE THREAD

**Issue by pandubalraj** [googlecodelabs/cloud-dialogflow-bqml#1]
Getting the following error when request given to BIGQuery

```
ERROR: { ApiError: Missing query parameter type
    at Object.parseHttpRespBody (/srv/node_modules/@google-cloud/common/src/util.js:193:30)
    at Object.handleResp (/srv/node_modules/@google-cloud/common/src/util.js:131:18)
    at /srv/node_modules/@google-cloud/common/src/util.js:496:12
    at Request.onResponse [as _callback] (/srv/node_modules/retry-request/index.js:198:7)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
  code: 400,
  errors: 
   [ { message: 'Missing query parameter type',
       domain: 'global',
       reason: 'invalid' } ],
  response: undefined,
  message: 'Missing query parameter type' }
```

**Comment by gmikels** [comment]
Thanks, this has been resolved by updating index.js. Parameters for the BigQuery Node.js client package had changed and a change to the fulfillment script was required.
